CREATE TABLE pos.devolucion_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    sesion_caja_id BIGINT NULL,
    folio VARCHAR(50) NOT NULL,
    motivo VARCHAR(250) NOT NULL,
    subtotal NUMERIC(14, 2) NOT NULL DEFAULT 0,
    descuento NUMERIC(14, 2) NOT NULL DEFAULT 0,
    impuesto NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total NUMERIC(14, 2) NOT NULL DEFAULT 0,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT devolucion_venta_venta_id_fkey
        FOREIGN KEY (venta_id)
        REFERENCES pos.venta(id),

    CONSTRAINT devolucion_venta_usuario_id_fkey
        FOREIGN KEY (usuario_id)
        REFERENCES pos.usuario(id),

    CONSTRAINT devolucion_venta_sesion_caja_id_fkey
        FOREIGN KEY (sesion_caja_id)
        REFERENCES pos.sesion_caja(id),

    CONSTRAINT devolucion_venta_folio_key
        UNIQUE (folio),

    CONSTRAINT devolucion_venta_subtotal_check
        CHECK (subtotal >= 0),

    CONSTRAINT devolucion_venta_descuento_check
        CHECK (descuento >= 0),

    CONSTRAINT devolucion_venta_impuesto_check
        CHECK (impuesto >= 0),

    CONSTRAINT devolucion_venta_total_check
        CHECK (total > 0)
);

CREATE INDEX idx_devolucion_venta_venta_fecha
    ON pos.devolucion_venta (
        venta_id,
        fecha DESC
    );

CREATE INDEX idx_devolucion_venta_usuario_fecha
    ON pos.devolucion_venta (
        usuario_id,
        fecha DESC
    );


CREATE TABLE pos.devolucion_venta_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_venta_id BIGINT NOT NULL,
    venta_detalle_id BIGINT NOT NULL,
    cantidad NUMERIC(14, 3) NOT NULL,
    subtotal_linea NUMERIC(14, 2) NOT NULL DEFAULT 0,
    descuento_importe NUMERIC(14, 2) NOT NULL DEFAULT 0,
    impuesto_importe NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_linea NUMERIC(14, 2) NOT NULL DEFAULT 0,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT devolucion_venta_detalle_devolucion_fkey
        FOREIGN KEY (devolucion_venta_id)
        REFERENCES pos.devolucion_venta(id)
        ON DELETE CASCADE,

    CONSTRAINT devolucion_venta_detalle_venta_detalle_fkey
        FOREIGN KEY (venta_detalle_id)
        REFERENCES pos.venta_detalle(id),

    CONSTRAINT devolucion_venta_detalle_cantidad_check
        CHECK (cantidad > 0),

    CONSTRAINT devolucion_venta_detalle_subtotal_check
        CHECK (subtotal_linea >= 0),

    CONSTRAINT devolucion_venta_detalle_descuento_check
        CHECK (descuento_importe >= 0),

    CONSTRAINT devolucion_venta_detalle_impuesto_check
        CHECK (impuesto_importe >= 0),

    CONSTRAINT devolucion_venta_detalle_total_check
        CHECK (total_linea > 0),

    CONSTRAINT uq_devolucion_detalle_venta_detalle
        UNIQUE (
            devolucion_venta_id,
            venta_detalle_id
        )
);

CREATE INDEX idx_devolucion_detalle_venta_detalle
    ON pos.devolucion_venta_detalle (
        venta_detalle_id
    );


CREATE TABLE pos.devolucion_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_venta_id BIGINT NOT NULL,
    venta_pago_id BIGINT NOT NULL,
    sesion_caja_id BIGINT NULL,
    monto NUMERIC(14, 2) NOT NULL,
    referencia VARCHAR(150) NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT devolucion_pago_devolucion_fkey
        FOREIGN KEY (devolucion_venta_id)
        REFERENCES pos.devolucion_venta(id)
        ON DELETE CASCADE,

    CONSTRAINT devolucion_pago_venta_pago_fkey
        FOREIGN KEY (venta_pago_id)
        REFERENCES pos.venta_pago(id),

    CONSTRAINT devolucion_pago_sesion_caja_fkey
        FOREIGN KEY (sesion_caja_id)
        REFERENCES pos.sesion_caja(id),

    CONSTRAINT devolucion_pago_monto_check
        CHECK (monto > 0),

    CONSTRAINT uq_devolucion_pago_venta_pago
        UNIQUE (
            devolucion_venta_id,
            venta_pago_id
        )
);

CREATE INDEX idx_devolucion_pago_devolucion
    ON pos.devolucion_pago (
        devolucion_venta_id
    );

CREATE INDEX idx_devolucion_pago_venta_pago
    ON pos.devolucion_pago (
        venta_pago_id
    );